dataroot: "../models/rve/" # Path to sample directory
event_dir: "../models/training_logs/"

# Delete later on!
#batch_size: 8
#d_loop: 10
#num_samples: 32000   # total number of training samples (adjust to your dataset)